# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeypots', '0002_auto_20170616_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeypot',
            name='team',
        ),
        migrations.DeleteModel(
            name='Honeypot',
        ),
    ]
