# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='honey_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assigned Honeypot ID'),
        ),
    ]
